### ISSUE TITLE
Get the player data

### ISSUE THREAD

**Issue by favasconcelos** [booxood/node-dota2-api#10]
Is there a method to return the player data, like the name, since all we have after calling getMatchDetails is the account_id (32-bit account ID) ?

**Comment by booxood** [comment]
Try going to the official document: https://wiki.teamfortress.com/wiki/WebAPI#Dota_2

**Comment by favasconcelos** [comment]
Hum, I do think that the best option should be https://wiki.teamfortress.com/wiki/WebAPI/GetPlayerSummaries, where i can pass all the Account Id's at once, 👍
