### ISSUE TITLE
The getTopLiveGame parameters parner ? 

### ISSUE THREAD

**Issue by EthanOrange** [booxood/node-dota2-api#2]
the parameters parner value what should be?

**Comment by booxood** [comment]
Refer to https://wiki.teamfortress.com/wiki/WebAPI/GetTopLiveGame, maybe can find some info.

**Comment by EthanOrange** [comment]
parner (int32)
Which partner's games to use.

Sorry i don't get it mean...

**Comment by booxood** [comment]
Me too...

**Comment by EthanOrange** [comment]
Nice shot...

**Comment by sentrythethird** [comment]
#3   Line 77 should read:
`var validOptionKeys = ['partner'];`
In my code I used partner = 1, which works but I am not sure what a partner is.

**Comment by booxood** [comment]
@sentrythethird You are right. There should be a typo.
