### ISSUE TITLE
GetScheduledLeagueGames not working

### ISSUE THREAD

**Issue by Ouradze** [booxood/node-dota2-api#8]
Hello,

Is this endpoint working ? It seems that when I use it : http://api.steampowered.com/IDOTA2Match_570/GetScheduledLeagueGames/v1/?key=key, I have this response.

"Not Found
Method 'GetScheduledLeagueGames' not found in interface 'IDOTA2Match_570'"

Have you ever managed to make it work ?

Thanks in advance

**Comment by booxood** [comment]
No, I can't help it.

Maybe DOTA2 don't support method 'GetScheduledLeagueGames'.

**Comment by Ouradze** [comment]
Ok, thanks for your answer !

**Comment by Ouradze** [comment]
I am closing this issue.
